var StudentsPresenceRepository = Base.extend({
    constructor: function() {
        this.studentsPresence = TAFFY([
        { id: 1, studentId: 1, subjectId: 1, totalAbsenseTime: 5, withValidReasonTime: 2, studying: true },
        { id: 2, studentId: 1, subjectId: 2, totalAbsenseTime: 15, withValidReasonTime: 6, studying: true },
        { id: 3, studentId: 1, subjectId: 3, totalAbsenseTime: 0, withValidReasonTime: 0, studying: true },
        { id: 4, studentId: 1, subjectId: 5, totalAbsenseTime: 8, withValidReasonTime: 7, studying: false },
        { id: 5, studentId: 2, subjectId: 1, totalAbsenseTime: 5, withValidReasonTime: 2, studying: true },
        { id: 6, studentId: 2, subjectId: 2, totalAbsenseTime: 8, withValidReasonTime: 5, studying: true },
        { id: 7, studentId: 2, subjectId: 7, totalAbsenseTime: 5, withValidReasonTime: 5, studying: true },
        { id: 8, studentId: 2, subjectId: 8, totalAbsenseTime: 7, withValidReasonTime: 3, studying: true },
        { id: 9, studentId: 2, subjectId: 4, totalAbsenseTime: 5, withValidReasonTime: 2, studying: true },
        { id: 10, studentId: 3, subjectId: 1, totalAbsenseTime: 15, withValidReasonTime: 5, studying: true },
        { id: 11, studentId: 4, subjectId: 2, totalAbsenseTime: 20, withValidReasonTime: 6, studying: true },
        { id: 12, studentId: 4, subjectId: 3, totalAbsenseTime: 14, withValidReasonTime: 10, studying: true },
        { id: 13, studentId: 5, subjectId: 2, totalAbsenseTime: 10, withValidReasonTime: 4, studying: true },
        { id: 14, studentId: 5, subjectId: 5, totalAbsenseTime: 2, withValidReasonTime: 2, studying: false },
        { id: 15, studentId: 5, subjectId: 7, totalAbsenseTime: 10, withValidReasonTime: 4, studying: true },
        { id: 16, studentId: 6, subjectId: 6, totalAbsenseTime: 13, withValidReasonTime: 6, studying: true },
        { id: 17, studentId: 6, subjectId: 8, totalAbsenseTime: 12, withValidReasonTime: 4, studying: true },
        { id: 18, studentId: 7, subjectId: 4, totalAbsenseTime: 6, withValidReasonTime: 2, studying: true },
        { id: 19, studentId: 8, subjectId: 1, totalAbsenseTime: 18, withValidReasonTime: 2, studying: true },
        { id: 20, studentId: 8, subjectId: 2, totalAbsenseTime: 22, withValidReasonTime: 10, studying: true },
        { id: 21, studentId: 8, subjectId: 5, totalAbsenseTime: 6, withValidReasonTime: 6, studying: true },
        { id: 22, studentId: 8, subjectId: 3, totalAbsenseTime: 2, withValidReasonTime: 0, studying: true },
        { id: 23, studentId: 8, subjectId: 4, totalAbsenseTime: 8, withValidReasonTime: 8, studying: true },
        { id: 24, studentId: 9, subjectId: 1, totalAbsenseTime: 7, withValidReasonTime: 3, studying: true },
        { id: 25, studentId: 9, subjectId: 2, totalAbsenseTime: 28, withValidReasonTime: 17, studying: true },
        { id: 26, studentId: 10, subjectId: 1, totalAbsenseTime: 9, withValidReasonTime: 6, studying: true },
        { id: 27, studentId: 10, subjectId: 2, totalAbsenseTime: 17, withValidReasonTime: 7, studying: true },
        { id: 28, studentId: 11, subjectId: 1, totalAbsenseTime: 4, withValidReasonTime: 2, studying: true },
        { id: 29, studentId: 12, subjectId: 3, totalAbsenseTime: 22, withValidReasonTime: 20, studying: true },
        { id: 30, studentId: 13, subjectId: 3, totalAbsenseTime: 4, withValidReasonTime: 4, studying: true },
        { id: 31, studentId: 14, subjectId: 2, totalAbsenseTime: 18, withValidReasonTime: 7, studying: true },
        { id: 32, studentId: 15, subjectId: 5, totalAbsenseTime: 2, withValidReasonTime: 0, studying: true },
        { id: 33, studentId: 16, subjectId: 5, totalAbsenseTime: 2, withValidReasonTime: 2, studying: true },
        { id: 34, studentId: 17, subjectId: 3, totalAbsenseTime: 6, withValidReasonTime: 4, studying: true },
        { id: 35, studentId: 18, subjectId: 2, totalAbsenseTime: 6, withValidReasonTime: 2, studying: true },
        { id: 36, studentId: 19, subjectId: 5, totalAbsenseTime: 2, withValidReasonTime: 1, studying: true },
        { id: 37, studentId: 19, subjectId: 6, totalAbsenseTime: 4, withValidReasonTime: 2, studying: false },
        { id: 38, studentId: 20, subjectId: 3, totalAbsenseTime: 5, withValidReasonTime: 4, studying: true },
        { id: 39, studentId: 20, subjectId: 2, totalAbsenseTime: 13, withValidReasonTime: 4, studying: true },
        { id: 40, studentId: 20, subjectId: 5, totalAbsenseTime: 2, withValidReasonTime: 2, studying: false },
        { id: 41, studentId: 20, subjectId: 6, totalAbsenseTime: 2, withValidReasonTime: 2, studying: true },
        { id: 42, studentId: 21, subjectId: 1, totalAbsenseTime: 12, withValidReasonTime: 8, studying: true },
        { id: 43, studentId: 21, subjectId: 2, totalAbsenseTime: 19, withValidReasonTime: 9, studying: true },
        { id: 44, studentId: 21, subjectId: 3, totalAbsenseTime: 16, withValidReasonTime: 12, studying: true },
        { id: 45, studentId: 21, subjectId: 4, totalAbsenseTime: 9, withValidReasonTime: 0, studying: true },
        { id: 46, studentId: 21, subjectId: 5, totalAbsenseTime: 6, withValidReasonTime: 4, studying: true },
        { id: 47, studentId: 21, subjectId: 6, totalAbsenseTime: 12, withValidReasonTime: 8, studying: true },
        { id: 48, studentId: 22, subjectId: 8, totalAbsenseTime: 20, withValidReasonTime: 18, studying: true },
        { id: 49, studentId: 22, subjectId: 1, totalAbsenseTime: 13, withValidReasonTime: 4, studying: true },
        { id: 50, studentId: 22, subjectId: 2, totalAbsenseTime: 14, withValidReasonTime: 5, studying: true },
        { id: 51, studentId: 22, subjectId: 3, totalAbsenseTime: 10, withValidReasonTime: 6, studying: true },
        { id: 52, studentId: 22, subjectId: 4, totalAbsenseTime: 8, withValidReasonTime: 2, studying: true },
        { id: 53, studentId: 22, subjectId: 5, totalAbsenseTime: 7, withValidReasonTime: 7, studying: true },
        { id: 54, studentId: 22, subjectId: 6, totalAbsenseTime: 10, withValidReasonTime: 5, studying: true },
        { id: 55, studentId: 23, subjectId: 1, totalAbsenseTime: 4, withValidReasonTime: 1, studying: true },
        { id: 56, studentId: 23, subjectId: 2, totalAbsenseTime: 14, withValidReasonTime: 8, studying: true },
        { id: 57, studentId: 23, subjectId: 3, totalAbsenseTime: 17, withValidReasonTime: 10, studying: true },
        { id: 58, studentId: 23, subjectId: 4, totalAbsenseTime: 0, withValidReasonTime: 0, studying: true },
        { id: 59, studentId: 23, subjectId: 5, totalAbsenseTime: 7, withValidReasonTime: 6, studying: true },
        { id: 60, studentId: 23, subjectId: 6, totalAbsenseTime: 4, withValidReasonTime: 2, studying: true },
        { id: 61, studentId: 23, subjectId: 8, totalAbsenseTime: 16, withValidReasonTime: 10, studying: true },
        { id: 62, studentId: 24, subjectId: 1, totalAbsenseTime: 5, withValidReasonTime: 1, studying: true },
        { id: 63, studentId: 24, subjectId: 7, totalAbsenseTime: 8, withValidReasonTime: 2, studying: true },
        { id: 64, studentId: 24, subjectId: 3, totalAbsenseTime: 16, withValidReasonTime: 14, studying: true },
        { id: 65, studentId: 24, subjectId: 4, totalAbsenseTime: 1, withValidReasonTime: 1, studying: true },
        { id: 66, studentId: 24, subjectId: 5, totalAbsenseTime: 6, withValidReasonTime: 4, studying: true },
        { id: 67, studentId: 24, subjectId: 6, totalAbsenseTime: 5, withValidReasonTime: 1, studying: true },
        { id: 68, studentId: 24, subjectId: 8, totalAbsenseTime: 12, withValidReasonTime: 10, studying: true },
        { id: 69, studentId: 25, subjectId: 1, totalAbsenseTime: 11, withValidReasonTime: 5, studying: true },
        { id: 70, studentId: 25, subjectId: 7, totalAbsenseTime: 9, withValidReasonTime: 5, studying: true },
        { id: 71, studentId: 25, subjectId: 3, totalAbsenseTime: 11, withValidReasonTime: 8, studying: true },
        { id: 72, studentId: 25, subjectId: 4, totalAbsenseTime: 5, withValidReasonTime: 3, studying: true },
        { id: 73, studentId: 25, subjectId: 5, totalAbsenseTime: 6, withValidReasonTime: 5, studying: true },
        { id: 74, studentId: 25, subjectId: 6, totalAbsenseTime: 8, withValidReasonTime: 5, studying: true },
        { id: 75, studentId: 25, subjectId: 8, totalAbsenseTime: 8, withValidReasonTime: 8, studying: true },
        { id: 76, studentId: 26, subjectId: 1, totalAbsenseTime: 13, withValidReasonTime: 6, studying: true },
        { id: 77, studentId: 26, subjectId: 7, totalAbsenseTime: 6, withValidReasonTime: 2, studying: true },
        { id: 78, studentId: 26, subjectId: 3, totalAbsenseTime: 20, withValidReasonTime: 18, studying: true },
        { id: 79, studentId: 26, subjectId: 4, totalAbsenseTime: 4, withValidReasonTime: 2, studying: true },
        { id: 80, studentId: 26, subjectId: 5, totalAbsenseTime: 7, withValidReasonTime: 3, studying: true },
        { id: 81, studentId: 26, subjectId: 6, totalAbsenseTime: 9, withValidReasonTime: 9, studying: true },
        { id: 82, studentId: 26, subjectId: 8, totalAbsenseTime: 4, withValidReasonTime: 2, studying: true },
        { id: 83, studentId: 27, subjectId: 1, totalAbsenseTime: 16, withValidReasonTime: 8, studying: true },
        { id: 84, studentId: 27, subjectId: 7, totalAbsenseTime: 8, withValidReasonTime: 4, studying: true },
        { id: 85, studentId: 27, subjectId: 3, totalAbsenseTime: 9, withValidReasonTime: 2, studying: true },
        { id: 86, studentId: 27, subjectId: 4, totalAbsenseTime: 5, withValidReasonTime: 1, studying: true },
        { id: 87, studentId: 27, subjectId: 5, totalAbsenseTime: 6, withValidReasonTime: 4, studying: true },
        { id: 88, studentId: 27, subjectId: 6, totalAbsenseTime: 9, withValidReasonTime: 1, studying: true },
        { id: 89, studentId: 27, subjectId: 8, totalAbsenseTime: 6, withValidReasonTime: 2, studying: true },
        { id: 90, studentId: 28, subjectId: 1, totalAbsenseTime: 16, withValidReasonTime: 8, studying: true },
        { id: 91, studentId: 28, subjectId: 7, totalAbsenseTime: 20, withValidReasonTime: 0, studying: true },
        { id: 92, studentId: 28, subjectId: 2, totalAbsenseTime: 24, withValidReasonTime: 4, studying: true },
        { id: 93, studentId: 28, subjectId: 4, totalAbsenseTime: 6, withValidReasonTime: 4, studying: true },
        { id: 94, studentId: 28, subjectId: 5, totalAbsenseTime: 6, withValidReasonTime: 0, studying: true },
        { id: 95, studentId: 28, subjectId: 6, totalAbsenseTime: 15, withValidReasonTime: 7, studying: true },
        { id: 96, studentId: 28, subjectId: 8, totalAbsenseTime: 14, withValidReasonTime: 12, studying: true },
        { id: 97, studentId: 29, subjectId: 1, totalAbsenseTime: 16, withValidReasonTime: 9, studying: true },
        { id: 98, studentId: 29, subjectId: 7, totalAbsenseTime: 18, withValidReasonTime: 15, studying: true },
        { id: 99, studentId: 29, subjectId: 3, totalAbsenseTime: 10, withValidReasonTime: 9, studying: true },
        { id: 100, studentId: 29, subjectId: 4, totalAbsenseTime: 6, withValidReasonTime: 2, studying: true },
        { id: 101, studentId: 29, subjectId: 5, totalAbsenseTime: 8, withValidReasonTime: 0, studying: true },
        { id: 102, studentId: 29, subjectId: 6, totalAbsenseTime: 8, withValidReasonTime: 5, studying: true },
        { id: 103, studentId: 29, subjectId: 8, totalAbsenseTime: 10, withValidReasonTime: 15, studying: true },
        { id: 104, studentId: 30, subjectId: 7, totalAbsenseTime: 5, withValidReasonTime: 3, studying: true },
        { id: 105, studentId: 30, subjectId: 3, totalAbsenseTime: 10, withValidReasonTime: 8, studying: true },
        { id: 106, studentId: 30, subjectId: 4, totalAbsenseTime: 2, withValidReasonTime: 0, studying: true },
        { id: 107, studentId: 30, subjectId: 5, totalAbsenseTime: 8, withValidReasonTime: 2, studying: true },
        { id: 108, studentId: 30, subjectId: 6, totalAbsenseTime: 9, withValidReasonTime: 4, studying: true },
        { id: 109, studentId: 30, subjectId: 8, totalAbsenseTime: 8, withValidReasonTime: 2, studying: true },
        { id: 110, studentId: 31, subjectId: 1, totalAbsenseTime: 12, withValidReasonTime: 7, studying: true },
        { id: 111, studentId: 31, subjectId: 7, totalAbsenseTime: 11, withValidReasonTime: 11, studying: true },
        { id: 112, studentId: 31, subjectId: 3, totalAbsenseTime: 13, withValidReasonTime: 9, studying: true },
        { id: 113, studentId: 31, subjectId: 4, totalAbsenseTime: 0, withValidReasonTime: 0, studying: true },
        { id: 114, studentId: 31, subjectId: 5, totalAbsenseTime: 4, withValidReasonTime: 2, studying: true },
        { id: 115, studentId: 31, subjectId: 6, totalAbsenseTime: 9, withValidReasonTime: 7, studying: true },
        { id: 116, studentId: 31, subjectId: 8, totalAbsenseTime: 4, withValidReasonTime: 2, studying: true },
        { id: 117, studentId: 32, subjectId: 3, totalAbsenseTime: 13, withValidReasonTime: 9, studying: true },
        { id: 118, studentId: 32, subjectId: 4, totalAbsenseTime: 2, withValidReasonTime: 1, studying: true },
        { id: 119, studentId: 32, subjectId: 5, totalAbsenseTime: 6, withValidReasonTime: 2, studying: true },
        { id: 120, studentId: 32, subjectId: 6, totalAbsenseTime: 5, withValidReasonTime: 3, studying: true },
        { id: 121, studentId: 33, subjectId: 8, totalAbsenseTime: 12, withValidReasonTime: 8, studying: true },
        { id: 122, studentId: 33, subjectId: 3, totalAbsenseTime: 6, withValidReasonTime: 6, studying: true },
        { id: 123, studentId: 33, subjectId: 4, totalAbsenseTime: 1, withValidReasonTime: 0, studying: true },
        { id: 124, studentId: 33, subjectId: 5, totalAbsenseTime: 7, withValidReasonTime: 3, studying: true },
        { id: 125, studentId: 34, subjectId: 6, totalAbsenseTime: 13, withValidReasonTime: 8, studying: true },
        { id: 126, studentId: 34, subjectId: 8, totalAbsenseTime: 14, withValidReasonTime: 4, studying: true },
        { id: 127, studentId: 34, subjectId: 3, totalAbsenseTime: 6, withValidReasonTime: 0, studying: true },
        { id: 128, studentId: 34, subjectId: 4, totalAbsenseTime: 7, withValidReasonTime: 3, studying: true },
        { id: 129, studentId: 35, subjectId: 5, totalAbsenseTime: 3, withValidReasonTime: 2, studying: true },
        { id: 130, studentId: 35, subjectId: 6, totalAbsenseTime: 5, withValidReasonTime: 5, studying: true },
        { id: 131, studentId: 35, subjectId: 8, totalAbsenseTime: 18, withValidReasonTime: 2, studying: true },
        { id: 132, studentId: 35, subjectId: 3, totalAbsenseTime: 12, withValidReasonTime: 5, studying: true },
        { id: 133, studentId: 36, subjectId: 4, totalAbsenseTime: 6, withValidReasonTime: 6, studying: true },
        { id: 134, studentId: 36, subjectId: 5, totalAbsenseTime: 7, withValidReasonTime: 6, studying: true },
        { id: 135, studentId: 36, subjectId: 6, totalAbsenseTime: 9, withValidReasonTime: 7, studying: true },
        { id: 136, studentId: 36, subjectId: 8, totalAbsenseTime: 16, withValidReasonTime: 1, studying: true },
        { id: 137, studentId: 37, subjectId: 4, totalAbsenseTime: 3, withValidReasonTime: 2, studying: true },
        { id: 138, studentId: 37, subjectId: 5, totalAbsenseTime: 5, withValidReasonTime: 4, studying: true },
        { id: 139, studentId: 37, subjectId: 6, totalAbsenseTime: 9, withValidReasonTime: 4, studying: true },
        { id: 140, studentId: 37, subjectId: 8, totalAbsenseTime: 6, withValidReasonTime: 4, studying: true },
        { id: 141, studentId: 38, subjectId: 4, totalAbsenseTime: 3, withValidReasonTime: 1, studying: true },
        { id: 142, studentId: 38, subjectId: 5, totalAbsenseTime: 6, withValidReasonTime: 2, studying: true },
        { id: 143, studentId: 38, subjectId: 6, totalAbsenseTime: 0, withValidReasonTime: 0, studying: true },
        { id: 144, studentId: 38, subjectId: 8, totalAbsenseTime: 9, withValidReasonTime: 5, studying: true },
        { id: 145, studentId: 39, subjectId: 4, totalAbsenseTime: 2, withValidReasonTime: 0, studying: true },
        { id: 146, studentId: 39, subjectId: 5, totalAbsenseTime: 5, withValidReasonTime: 1, studying: true },
        { id: 147, studentId: 39, subjectId: 6, totalAbsenseTime: 4, withValidReasonTime: 4, studying: true },
        { id: 148, studentId: 39, subjectId: 8, totalAbsenseTime: 11, withValidReasonTime: 7, studying: true },
        { id: 149, studentId: 40, subjectId: 4, totalAbsenseTime: 6, withValidReasonTime: 2, studying: true },
        { id: 150, studentId: 40, subjectId: 5, totalAbsenseTime: 6, withValidReasonTime: 5, studying: true },
        { id: 151, studentId: 40, subjectId: 6, totalAbsenseTime: 5, withValidReasonTime: 2, studying: true },
        { id: 152, studentId: 40, subjectId: 8, totalAbsenseTime: 6, withValidReasonTime: 5, studying: true },
        { id: 153, studentId: 41, subjectId: 1, totalAbsenseTime: 8, withValidReasonTime: 7, studying: true },
        { id: 154, studentId: 41, subjectId: 2, totalAbsenseTime: 26, withValidReasonTime: 23, studying: true },
        { id: 155, studentId: 41, subjectId: 3, totalAbsenseTime: 6, withValidReasonTime: 2, studying: true },
        { id: 156, studentId: 41, subjectId: 4, totalAbsenseTime: 6, withValidReasonTime: 5, studying: true },
        { id: 157, studentId: 41, subjectId: 5, totalAbsenseTime: 3, withValidReasonTime: 1, studying: true },
        { id: 158, studentId: 41, subjectId: 6, totalAbsenseTime: 6, withValidReasonTime: 1, studying: true },
        { id: 159, studentId: 41, subjectId: 7, totalAbsenseTime: 16, withValidReasonTime: 5, studying: true },
        { id: 160, studentId: 41, subjectId: 8, totalAbsenseTime: 3, withValidReasonTime: 1, studying: true },
        { id: 161, studentId: 3, subjectId: 2, totalAbsenseTime: 15, withValidReasonTime: 14, studying: true },
        { id: 162, studentId: 3, subjectId: 5, totalAbsenseTime: 5, withValidReasonTime: 2, studying: true },
        { id: 163, studentId: 3, subjectId: 7, totalAbsenseTime: 11, withValidReasonTime: 6, studying: true },
        { id: 164, studentId: 7, subjectId: 2, totalAbsenseTime: 5, withValidReasonTime: 2, studying: true },
        { id: 165, studentId: 7, subjectId: 5, totalAbsenseTime: 3, withValidReasonTime: 0, studying: true },
        { id: 166, studentId: 7, subjectId: 7, totalAbsenseTime: 19, withValidReasonTime: 5, studying: true },
        { id: 167, studentId: 11, subjectId: 2, totalAbsenseTime: 17, withValidReasonTime: 15, studying: true },
        { id: 168, studentId: 11, subjectId: 5, totalAbsenseTime: 5, withValidReasonTime: 4, studying: true },
        { id: 169, studentId: 11, subjectId: 7, totalAbsenseTime: 4, withValidReasonTime: 1, studying: true },
        { id: 170, studentId: 12, subjectId: 2, totalAbsenseTime: 5, withValidReasonTime: 2, studying: true },
        { id: 171, studentId: 12, subjectId: 5, totalAbsenseTime: 4, withValidReasonTime: 3, studying: true },
        { id: 172, studentId: 12, subjectId: 7, totalAbsenseTime: 14, withValidReasonTime: 7, studying: true },
        { id: 173, studentId: 13, subjectId: 2, totalAbsenseTime: 17, withValidReasonTime: 17, studying: true },
        { id: 174, studentId: 13, subjectId: 6, totalAbsenseTime: 5, withValidReasonTime: 4, studying: true },
        { id: 175, studentId: 13, subjectId: 7, totalAbsenseTime: 14, withValidReasonTime: 13, studying: true },
        { id: 176, studentId: 14, subjectId: 3, totalAbsenseTime: 13, withValidReasonTime: 9, studying: true },
        { id: 177, studentId: 14, subjectId: 5, totalAbsenseTime: 7, withValidReasonTime: 3, studying: true },
        { id: 178, studentId: 14, subjectId: 7, totalAbsenseTime: 6, withValidReasonTime: 6, studying: true },
        { id: 179, studentId: 15, subjectId: 2, totalAbsenseTime: 17, withValidReasonTime: 1, studying: true },
        { id: 180, studentId: 15, subjectId: 8, totalAbsenseTime: 16, withValidReasonTime: 7, studying: true },
        { id: 181, studentId: 15, subjectId: 7, totalAbsenseTime: 6, withValidReasonTime: 3, studying: true },
        { id: 182, studentId: 16, subjectId: 2, totalAbsenseTime: 11, withValidReasonTime: 4, studying: true },
        { id: 183, studentId: 16, subjectId: 8, totalAbsenseTime: 4, withValidReasonTime: 1, studying: true },
        { id: 184, studentId: 16, subjectId: 7, totalAbsenseTime: 7, withValidReasonTime: 4, studying: true },
        { id: 185, studentId: 17, subjectId: 2, totalAbsenseTime: 8, withValidReasonTime: 2, studying: true },
        { id: 186, studentId: 17, subjectId: 5, totalAbsenseTime: 5, withValidReasonTime: 2, studying: true },
        { id: 187, studentId: 17, subjectId: 7, totalAbsenseTime: 6, withValidReasonTime: 1, studying: true },
        { id: 188, studentId: 18, subjectId: 4, totalAbsenseTime: 5, withValidReasonTime: 2, studying: true },
        { id: 189, studentId: 18, subjectId: 5, totalAbsenseTime: 2, withValidReasonTime: 1, studying: true },
        { id: 190, studentId: 18, subjectId: 7, totalAbsenseTime: 5, withValidReasonTime: 2, studying: true },
        { id: 191, studentId: 19, subjectId: 2, totalAbsenseTime: 8, withValidReasonTime: 7, studying: true },
        { id: 192, studentId: 19, subjectId: 3, totalAbsenseTime: 18, withValidReasonTime: 1, studying: true },
        { id: 193, studentId: 19, subjectId: 7, totalAbsenseTime: 14, withValidReasonTime: 10, studying: true }
        ]);
    this.lastId = this.studentsPresence().get().length;
    },
    save: function (subjectInfo, studentId) {
        for (var i = 0; i < subjectInfo.length; i++) {
            var found = this.studentsPresence({ subjectId: subjectInfo[i].id, studentId: studentId });
            var studentPresence = found.first();
            if (studentPresence)
                found.update({ studying: subjectInfo[i].studying });
            else if (subjectInfo[i].studying) {
                this.studentsPresence.insert({
                    id: this.lastId + 1,
                    studentId: studentId,
                    subjectId: subjectInfo[i].id,
                    totalAbsenseTime: 0,
                    withValidReasonTime: 0,
                    studying: true
                });
                this.lastId++;
            }
        }
    },
    getByStudentId: function (id) {
        return Helpers.deepCopy(this.studentsPresence({ studentId: id }).get());
    },
    getAll: function () {
        return Helpers.deepCopy(this.studentsPresence().get());
    }
});